#!/usr/bin/env bash
# Set up HTTPS for the renovatie app on the Docker host, using the host's nginx
# as TLS terminator (the app container itself stays plain HTTP on $PORT).
#
#   - Generates a local CA in ./tls/ (once) and a server certificate whose SANs
#     cover the host's name variants and LAN/Tailscale IPs. Re-run to renew.
#   - Installs the certificate and an nginx vhost on $HTTPS_PORT proxying to
#     127.0.0.1:$PORT, and opens the firewall port.
#   - Prints how to trust ./tls/ca.crt on client machines.
#
# Usage: ./setup-https.sh
# Configuration (via .env or environment, like deploy.sh):
#   DEPLOY_HOST  SSH host running the app   (required)
#   PORT         app port on the host       (default: 5567)
#   HTTPS_PORT   TLS port to serve          (default: 8443)
#   EXTRA_SANS   extra SAN entries, comma-separated openssl syntax,
#                e.g. "DNS:renovatie.home,IP:192.168.2.99"
set -euo pipefail
cd "$(dirname "$0")"

[ -f .env ] && . ./.env

HOST="${DEPLOY_HOST:?DEPLOY_HOST is not set — copy .env.example to .env and edit it, or export DEPLOY_HOST}"
PORT="${PORT:-5567}"
HTTPS_PORT="${HTTPS_PORT:-8443}"
TLS_DIR=tls
CA_DAYS=3650
CERT_DAYS=825  # maximum many TLS clients accept for leaf certificates

mkdir -p "$TLS_DIR"

# --- 1. Local CA (created once; ca.crt is what client machines must trust) ---
if [ ! -f "$TLS_DIR/ca.key" ]; then
  echo "==> Generating local CA in $TLS_DIR/ ..."
  openssl req -x509 -newkey ec -pkeyopt ec_paramgen_curve:P-256 -sha256 \
    -days "$CA_DAYS" -nodes \
    -keyout "$TLS_DIR/ca.key" -out "$TLS_DIR/ca.crt" \
    -subj "/CN=Renovatie Local CA" \
    -addext "basicConstraints=critical,CA:TRUE,pathlen:0" \
    -addext "keyUsage=critical,keyCertSign,cRLSign"
  chmod 600 "$TLS_DIR/ca.key"
fi

# --- 2. Server certificate with SANs derived from the host -------------------
SHORT_NAME=$(ssh "$HOST" hostname)
SANS="DNS:$SHORT_NAME,DNS:$SHORT_NAME.local,DNS:$SHORT_NAME.lan,DNS:$SHORT_NAME.home"
# Global IPv4 addresses, skipping docker bridges (172.16.0.0/12).
for ip in $(ssh "$HOST" "ip -4 -o addr show scope global" | awk '{split($4, a, "/"); print a[1]}'); do
  case "$ip" in 172.1[6-9].* | 172.2?.* | 172.3[01].*) continue ;; esac
  SANS="$SANS,IP:$ip"
done
[ -n "${EXTRA_SANS:-}" ] && SANS="$SANS,$EXTRA_SANS"
echo "==> Issuing server certificate for: $SANS"

openssl req -newkey ec -pkeyopt ec_paramgen_curve:P-256 -sha256 -nodes \
  -keyout "$TLS_DIR/server.key" -out "$TLS_DIR/server.csr" \
  -subj "/CN=$SHORT_NAME"
openssl x509 -req -in "$TLS_DIR/server.csr" \
  -CA "$TLS_DIR/ca.crt" -CAkey "$TLS_DIR/ca.key" -CAcreateserial \
  -days "$CERT_DAYS" -sha256 \
  -extfile <(printf "subjectAltName=%s\nkeyUsage=critical,digitalSignature\nextendedKeyUsage=serverAuth\nbasicConstraints=CA:FALSE\n" "$SANS") \
  -out "$TLS_DIR/server.crt"
rm -f "$TLS_DIR/server.csr"
chmod 600 "$TLS_DIR/server.key"

# --- 3. Install certificate + nginx vhost on the host ------------------------
echo "==> Installing certificate and nginx vhost on $HOST ..."
scp -q "$TLS_DIR/ca.crt" "$TLS_DIR/server.crt" "$TLS_DIR/server.key" "$HOST:/tmp/"
ssh "$HOST" HTTPS_PORT="$HTTPS_PORT" PORT="$PORT" SHORT_NAME="$SHORT_NAME" bash -s <<'EOF'
set -euo pipefail
sudo -n install -d -m 755 /etc/nginx/ssl/renovatie
sudo -n install -m 644 /tmp/ca.crt /etc/nginx/ssl/renovatie/ca.crt
sudo -n install -m 644 /tmp/server.crt /etc/nginx/ssl/renovatie/server.crt
sudo -n install -m 600 /tmp/server.key /etc/nginx/ssl/renovatie/server.key
rm -f /tmp/ca.crt /tmp/server.crt /tmp/server.key

sudo -n tee /etc/nginx/conf.d/renovatie-tls.conf >/dev/null <<NGINX
# HTTPS for the renovatie app — generated by renovatie/setup-https.sh; edits are overwritten.
server {
    listen $HTTPS_PORT ssl;
    listen [::]:$HTTPS_PORT ssl;
    http2 on;
    server_name $SHORT_NAME;

    ssl_certificate     /etc/nginx/ssl/renovatie/server.crt;
    ssl_certificate_key /etc/nginx/ssl/renovatie/server.key;

    client_max_body_size 25m;  # image uploads in comments

    # Public trust anchor only; the matching private key stays on the machine
    # that runs this setup script and is never copied to the host.
    location = /renovatie-ca.crt {
      alias /etc/nginx/ssl/renovatie/ca.crt;
      default_type application/x-x509-ca-cert;
      add_header Content-Disposition 'attachment; filename="renovatie-ca.crt"';
    }

    proxy_http_version 1.1;
    # \$http_host keeps the port, so app-generated absolute URLs stay correct.
    proxy_set_header Host \$http_host;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    # MCP streamable HTTP can hold responses open; don't buffer or time out.
    proxy_buffering off;
    proxy_read_timeout 1h;

    # Starlette 307-redirects /api/mcp to /api/mcp/ with an absolute URL that
    # loses the https scheme behind the proxy; skip it by proxying straight to
    # the trailing-slash path.
    location = /api/mcp {
        proxy_pass http://127.0.0.1:$PORT/api/mcp/;
    }

    location / {
        proxy_pass http://127.0.0.1:$PORT;
    }
}
NGINX

# This host's nginx.conf does not include conf.d/*; include exactly our vhost
# (a blanket conf.d/*.conf include would activate unrelated leftover configs).
if ! sudo -n grep -q "conf\.d/renovatie-tls\.conf" /etc/nginx/nginx.conf; then
  sudo -n sed -i '/^http {/a\    include /etc/nginx/conf.d/renovatie-tls.conf;' /etc/nginx/nginx.conf
fi

sudo -n nginx -t
sudo -n systemctl reload nginx

if command -v firewall-cmd >/dev/null 2>&1 && sudo -n firewall-cmd --state >/dev/null 2>&1; then
  sudo -n firewall-cmd --permanent --add-port="$HTTPS_PORT"/tcp >/dev/null
  sudo -n firewall-cmd --reload >/dev/null
  echo "firewalld: opened $HTTPS_PORT/tcp"
fi
EOF

# --- 4. Verify ----------------------------------------------------------------
echo "==> Verifying ..."
curl -fsS --cacert "$TLS_DIR/ca.crt" "https://$SHORT_NAME:$HTTPS_PORT/api/" >/dev/null
echo "OK: https://$SHORT_NAME:$HTTPS_PORT/ serves the app with a valid certificate chain"
CA_FINGERPRINT=$(openssl x509 -in "$TLS_DIR/ca.crt" -noout -fingerprint -sha256 | cut -d= -f2)

cat <<MSG

Done. Clients can download the public CA from:
  https://$SHORT_NAME:$HTTPS_PORT/renovatie-ca.crt

Share this SHA-256 fingerprint through a channel users already trust, and ask
them to verify it before installing the certificate:
  $CA_FINGERPRINT

Clients must trust $TLS_DIR/ca.crt (once):
  Windows:  certutil.exe -user -addstore Root tls\\ca.crt   (or double-click ca.crt →
            Install Certificate → Current User → Trusted Root Certification Authorities)
  Linux/WSL: sudo cp $TLS_DIR/ca.crt /usr/local/share/ca-certificates/renovatie-ca.crt && sudo update-ca-certificates
  Android/iOS: send ca.crt to the device and install it as a CA certificate.

App URL:  https://$SHORT_NAME:$HTTPS_PORT/
MCP URL:  https://$SHORT_NAME:$HTTPS_PORT/api/mcp
MSG
